/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jcombobboxandradiobutton;

import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Selcuk
 */
public class RadioVeComboBox extends javax.swing.JFrame {

    Set<String> diller=new LinkedHashSet<String>();
    
    
    
    /**
     * Creates new form RadioVeComboBox
     */
    public RadioVeComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        javaRadio = new javax.swing.JRadioButton();
        phytonRadio = new javax.swing.JRadioButton();
        phpRadio = new javax.swing.JRadioButton();
        dilGoster = new javax.swing.JButton();
        cBDiller = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(javaRadio);
        javaRadio.setText("Java");

        buttonGroup1.add(phytonRadio);
        phytonRadio.setText("Phyton");

        buttonGroup1.add(phpRadio);
        phpRadio.setText("Php");

        dilGoster.setText("Göster");
        dilGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dilGosterActionPerformed(evt);
            }
        });

        cBDiller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phyton", "Java", "C++", "Php" }));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phpRadio)
                    .addComponent(phytonRadio)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(javaRadio)
                            .addComponent(dilGoster))
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(cBDiller, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(javaRadio)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cBDiller)))
                .addGap(18, 18, 18)
                .addComponent(phytonRadio)
                .addGap(18, 18, 18)
                .addComponent(phpRadio)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dilGoster)
                    .addComponent(jButton1))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void goster(){
        
        String mesaj="Şu diller seçildi.";
        
        for(String dil:diller){
            
            mesaj+=dil+" ";
            
        }
        JOptionPane.showMessageDialog(this, mesaj);
        
    }
    
    private void dilGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dilGosterActionPerformed
        if(javaRadio.isSelected()){
            diller.add("Java");
        }else{
            diller.remove("Java");
        }
        if(phytonRadio.isSelected()){
            diller.add("Phyton");
        }else{
            diller.remove("Phyton");
        }
        if(phpRadio.isSelected()){
            diller.add("Php");
        }else{
            diller.remove("Php");
        }
        
        goster();
        
    }//GEN-LAST:event_dilGosterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String mesaj="Şu dil seçildi : "+cBDiller.getSelectedItem();
        
        JOptionPane.showMessageDialog(this, mesaj);
        
                    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioVeComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioVeComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioVeComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioVeComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioVeComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cBDiller;
    private javax.swing.JButton dilGoster;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton javaRadio;
    private javax.swing.JRadioButton phpRadio;
    private javax.swing.JRadioButton phytonRadio;
    // End of variables declaration//GEN-END:variables
}
